version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - servernetwork
  backend:
    build: .
    ports:
      - "8112:80"
    container_name: spring-treen-green
    environment:
      - TZ=Asia/Seoul
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - servernetwork
    depends_on:
      - redis

networks:
  servernetwork:
    external: true
    driver: bridge