version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - servernetwork
  backend:
    # 현재 디렉토리에서의 Dockerfile을 사용하여 Docker 이미지를 빌드
    build: .
    # 호스트의 8111 포트와 컨테이너의 80 포트를 매핑
    ports:
      - "8111:80"
    # 컨테이너의 이름
    container_name: spring-treen-blue
    environment:
      - TZ=Asia/Seoul
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - servernetwork

networks:
  servernetwork:
    external: true
    driver: bridge